import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css"
import AppWalletProvider from "../lib/AppWalletProvider";
import Appbar from "@/components/Appbar";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "TokenNx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppWalletProvider>

        <Toaster
          position="top-right"
          
          toastOptions={{
            style: {
              borderRadius: '2px',
              background: '#1f2937',
              color: '#9ca3af',
              padding: '12px',
            },
          }}
          />
          <Appbar/>
          {children}
        </AppWalletProvider>
      </body>
    </html>
  );
}
